# Hypeterm — set up the relay, this machine, and a paired phone.
#
#   just up          deploy the relay and enrol this machine (asks what it needs)
#   just run         host a shell and mirror it
#   just pair        print a pairing code for a phone
#
# This file is the onboarding path across the three projects. Each project keeps its
# own: server/justfile is the full operator interface for a deployed relay, and the
# recipes here delegate to it rather than restating it.

set shell := ["bash", "-euo", "pipefail", "-c"]

env_file := "server/deploy/.env"
publisher := "publisher/target/release/hypeterm-publish"

_default:
    @just --list --unsorted

# ------------------------------------------------------------------ onboarding

# Deploy the relay and enrol this machine (MODE: local, tailscale, proxy or tls; asked if omitted).
up mode="":
    #!/usr/bin/env bash
    set -euo pipefail

    interactive=false
    [[ -t 0 ]] && interactive=true

    # Prompts go to stderr (bash `read -p` does this), so the answer is what a
    # $(...) capture receives. With no terminal — CI, a pipe — every question takes
    # its default instead of hanging forever on a read that can never be answered.
    ask() {
      local prompt="$1" default="${2:-}" reply=""
      if [[ "$interactive" != true ]]; then echo "$default"; return; fi
      read -r -p "$prompt" reply || true
      echo "${reply:-$default}"
    }
    ask_secret() {
      local prompt="$1" reply=""
      if [[ "$interactive" != true ]]; then echo ""; return; fi
      read -rs -p "$prompt" reply || true
      echo >&2
      echo "$reply"
    }

    just _doctor

    # ---- which posture -----------------------------------------------------
    mode="{{mode}}"
    if [[ -z "$mode" && -f "{{env_file}}" ]]; then
      mode=$(grep '^RELAY_MODE=' "{{env_file}}" | cut -d= -f2- || true)
      [[ -n "$mode" ]] && echo "==> redeploying the remembered mode: $mode"
    fi
    if [[ -z "$mode" ]]; then
      say() { echo "$1" >&2; }
      say ""
      say "      How should the relay be reachable? This is the one decision it cannot"
      say "      make for you, and it is remembered afterwards."
      say ""
      say "        1  local      loopback only, no TLS. Development and single-machine use."
      say "        2  tailscale  joins your tailnet: your devices only, with a real certificate."
      say "        3  proxy      behind a TLS-terminating reverse proxy you already run."
      say "        4  tls        TLS terminated in-process from a certificate you supply."
      say ""
      case "$(ask '      choose [1]: ' 1)" in
        1|local|"")  mode=local ;;
        2|tailscale) mode=tailscale ;;
        3|proxy)     mode=proxy ;;
        4|tls)       mode=tls ;;
        *) echo "not one of the four options" >&2; exit 1 ;;
      esac
      echo >&2
    fi

    case "$mode" in
      local|tailscale|proxy|tls) ;;
      *) echo "unknown mode: $mode (expected local, tailscale, proxy or tls)" >&2; exit 1 ;;
    esac

    # ---- whatever that posture needs from a human --------------------------
    # These are exported rather than written to deploy/.env first: the relay's own
    # bootstrap secrets are generated by server/justfile on the run that finds no
    # env file, so creating one here would leave it with no key to encrypt with.
    # They are persisted below, once that file exists.
    # Anything a person supplied on an earlier run is already in the env file. Read it
    # back and export it, so a redeploy asks nothing a second time and the child sees
    # the values in its environment rather than only through its own read of the file.
    source "{{env_file}}" 2>/dev/null || true
    [[ -n "${TS_AUTHKEY:-}" ]] && export TS_AUTHKEY
    [[ -n "${RELAY_PUBLIC_ORIGIN:-}" ]] && export RELAY_PUBLIC_ORIGIN
    true

    case "$mode" in
      tailscale)
        if [[ -z "${TS_AUTHKEY:-}" ]]; then
          echo "      A tailnet needs authenticating once. An auth key makes this" >&2
          echo "      unattended; without one you get a login link to click, which" >&2
          echo "      works just as well. Keys are made at" >&2
          echo "      https://login.tailscale.com/admin/settings/keys" >&2
          echo "" >&2
          TS_AUTHKEY=$(ask_secret '      TS_AUTHKEY (blank to log in by hand): ')
          export TS_AUTHKEY
        fi
        ;;
      proxy)
        if [[ -z "${RELAY_PUBLIC_ORIGIN:-}" ]]; then
          echo "      The public URL your proxy serves — the address the phone will use." >&2
          RELAY_PUBLIC_ORIGIN=$(ask '      RELAY_PUBLIC_ORIGIN [https://localhost]: ' "https://localhost")
          export RELAY_PUBLIC_ORIGIN
        fi
        ;;
      tls)
        if [[ ! -f server/deploy/tls/cert.pem ]]; then
          echo "      No certificate in server/deploy/tls/." >&2
          host=$(ask '      generate a self-signed one for which host? [localhost]: ' localhost)
          (cd server && just tls-selfsigned "$host")
          echo "      Self-signed: a release build of the Android client will refuse it." >&2
        fi
        ;;
    esac

    # ---- deploy ------------------------------------------------------------
    (cd server && just up "$mode")

    # Now that the file exists, remember the answers so the next deploy is silent.
    [[ -n "${TS_AUTHKEY:-}" ]] && just _remember TS_AUTHKEY "$TS_AUTHKEY"
    [[ -n "${RELAY_PUBLIC_ORIGIN:-}" ]] && just _remember RELAY_PUBLIC_ORIGIN "$RELAY_PUBLIC_ORIGIN"

    # ---- enrol this machine ------------------------------------------------
    url=$(just _relay-url)
    if [[ ! -x "{{publisher}}" ]] || ! "{{publisher}}" status 2>/dev/null | grep -q '^relay '; then
      answer=$(ask "      Enrol this machine as a publisher against ${url}? [Y/n] " Y)
      if [[ "$answer" =~ ^[Yy]?$ ]]; then
        # The relay is already up by this point, so a failure here is a smaller thing
        # than it looks: it is worth reporting and worth retrying, but it is not a
        # failed deployment and should not be reported as one.
        if just enroll; then
          echo
          echo "      Pair a phone by pasting this into its pairing screen:"
          echo
          just pair
        else
          echo
          echo "      The relay is up, but enrolling this machine failed. Retry with:" >&2
          echo "        just enroll" >&2
        fi
      fi
    fi

    echo
    echo "      Ready. Host a mirrored shell with:  just run"
    if [[ "$mode" == "local" ]]; then
      echo
      echo "      NOTE: local mode is loopback only, so a phone cannot reach it over the"
      echo "            network. Either use 'adb reverse tcp:8080 tcp:8080' with a USB"
      echo "            device, or redeploy with 'just up tailscale'."
    fi
    echo

# Build the publisher and register this machine with the deployed relay.
enroll:
    #!/usr/bin/env bash
    set -euo pipefail
    echo "==> building the publisher"
    (cd publisher && cargo build --release)
    "{{publisher}}" enroll --relay "$(just _relay-url)"

# Print a pairing code for a phone. Treat it like a password; it expires in minutes.
pair:
    @{{publisher}} pair-code --url "$(just _relay-url)"

# Host a terminal and mirror it: `just run`, or `just run --label build -- cargo test`.
run *args:
    @{{publisher}} run {{args}}

# What this machine has enrolled, and what it is publishing.
publishing:
    @{{publisher}} status && echo && {{publisher}} list

# ------------------------------------------------------------------- the relay

# Container, health and readiness of the relay.
status:
    @cd server && just status

# Follow the relay's logs.
logs lines="100":
    @cd server && just logs {{lines}}

# The operator token, for the relay's admin API.
token:
    @cd server && just token

# Stop the relay, keeping its data.
down:
    @cd server && just down

# Stop the relay and permanently delete every identity, device and terminal.
destroy:
    @cd server && just destroy

# --------------------------------------------------------------- development

# Build the Android APK. Needs the SDK/NDK — see android/docs/android-build.md.
apk:
    #!/usr/bin/env bash
    set -euo pipefail
    if [[ ! -d "${HOME}/.cache/hypeterm/openssl-android" ]]; then
      echo "OpenSSL for Android is missing; building it once (this takes a while)."
      (cd android && tools/build-openssl-android.sh)
    fi
    (cd android && ./gradlew :app:assembleDebug)

# Every test suite: the relay, the publisher, and the client core.
test:
    #!/usr/bin/env bash
    set -euo pipefail
    (cd server && cargo test)
    (cd publisher && cargo test)
    (cd android && cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build -j && ctest --test-dir build --output-on-failure)

# ------------------------------------------------------------------ internals

# Fail early, and with something actionable, rather than midway through a deploy.
_doctor:
    #!/usr/bin/env bash
    set -euo pipefail
    missing=()
    command -v docker >/dev/null || missing+=("docker — https://docs.docker.com/engine/install/")
    docker compose version >/dev/null 2>&1 || missing+=("docker compose v2 (the 'compose' plugin)")
    command -v cargo >/dev/null || missing+=("cargo — https://rustup.rs")
    command -v openssl >/dev/null || missing+=("openssl")
    if (( ${#missing[@]} )); then
      echo "missing prerequisites:" >&2
      printf '  - %s\n' "${missing[@]}" >&2
      exit 1
    fi
    docker info >/dev/null 2>&1 || { echo "docker is installed but not running (or this user cannot reach it)" >&2; exit 1; }

# The address the relay answers on, derived from the deployment it remembers.
_relay-url:
    #!/usr/bin/env bash
    set -euo pipefail
    if [[ ! -f "{{env_file}}" ]]; then
      echo "no relay deployed yet — run: just up" >&2
      exit 1
    fi
    source "{{env_file}}"
    case "${RELAY_MODE:-local}" in
      tailscale) echo "https://${RELAY_TS_NAME}" ;;
      proxy)     echo "${RELAY_PUBLIC_ORIGIN:-https://localhost}" ;;
      tls)       echo "https://127.0.0.1:${RELAY_PORT:-8080}" ;;
      *)         echo "http://127.0.0.1:${RELAY_PORT:-8080}" ;;
    esac

# Persist one answer into the relay's env file, which stays mode 0600 and uncommitted.
_remember key value:
    #!/usr/bin/env bash
    set -euo pipefail
    [[ -f "{{env_file}}" ]] || exit 0
    if grep -q "^{{key}}=" "{{env_file}}"; then
      sed -i "s|^{{key}}=.*|{{key}}={{value}}|" "{{env_file}}"
    else
      echo "{{key}}={{value}}" >> "{{env_file}}"
    fi
    chmod 600 "{{env_file}}"
